export { default as TopBanner } from "./top-banner"
export { default as CategoryWithSlide } from "./category-with-slide"
export { default as CategoryWithBanner } from "./category-with-banner"
export { default as CategoryVideo } from "./category-video"
export { default as CategoryWithColumns } from "./category-with-columns"
export { default as CategoryText } from "./category-text"
export { default as TextNews } from "./text-news"
export { default as Yangiliklar } from "./yangiliklar"