export type EditorToolId =
  | "undo"
  | "redo"
  | "bold"
  | "italic"
  | "underline"
  | "strike"
  | "sub"
  | "sup"
  | "code"
  | "h1"
  | "h2"
  | "h3"
  | "link"
  | "quote"
  | "bullet"
  | "numbered"
  | "alignLeft"
  | "alignCenter"
  | "alignRight"
  | "color"
  | "bg"
  | "font"
  | "image"
  | "video"
  | "audio"
  | "caption"

export type MobileViewMode = "edit" | "preview" | "split"

export type RichTextColor =
  | "red"
  | "blue"
  | "green"
  | "orange"
  | "purple"
  | "gray"
  | ""

export type RichTextBg = "yellow" | "cyan" | "green" | "pink" | "gray" | "none" | ""

export type RichTextFont =
  | "sans"
  | "serif"
  | "mono"
  | "inter"
  | "georgia"
  | "display"
  | ""
