export const seedNews = {
  news: [
    {
      title: "Nike Air Max 270",
      description: "The Nike Air Max 270 is a modern sneaker that combines comfort and style.",
      content: [
        { type: "paragraph", text: "The Nike Air Max 270 is a modern sneaker that combines comfort and style. It features a large Air unit for all-day cushioning." },
        { type: "image", src: "/images/news/image-1.png", alt: "Nike Air Max 270 side view" },
        { type: "quote", text: "The most comfortable Air Max we've ever made.", author: "Nike Design Team" },
        { type: "paragraph", text: "Available in multiple colorways. Learn more at the official store. Available in multiple colorways. Learn more at the official store.Available in multiple colorways. Learn more at the official store.Available in multiple colorways. Learn more at the official store.Available in multiple colorways. Learn more at the official store.Available in multiple colorways. Learn more at the official store.Available in multiple colorways. Learn more at the official store." },
        { type: "video", source: "youtube", url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ" },
        { type: "paragraph", text: "Available in multiple colorways. Learn more at the official store. Available in multiple colorways. Learn more at the official store.Available in multiple colorways. Learn more at the official store.Available in multiple colorways. Learn more at the official store.Available in multiple colorways. Learn more at the official store.Available in multiple colorways. Learn more at the official store." },
        { type: "video", source: "local", url: "/videos/news/video-1.mp4" },
        { type: "paragraph", text: "Available in multiple colorways. Learn more at the official store. Available in multiple colorways. Learn more at the official store.Available in multiple colorways. Learn more at the official store.Available in multiple colorways. Learn more at the official store.Available in multiple colorways. Learn more at the official store.Available in multiple colorways. Learn more at the official store.Available in multiple colorways. Learn more at the official store." },
        { type: "link", href: "https://www.nike.com", text: "Nike Official Store" },
      ],
      tags: ["Nike", "Air Max", "270"],
      slug: "nike-air-max-270",
      category: "Sports",
      images: ["/images/news/image-1.png", "/images/news/image-2.png", "/images/news/image-3.png"],
      author: "John Doe",
      minutes: 3,
      views: 100,
      status: "published",
      type: "video",
      authorsChoice: true,
      isTrending: false,
      isLatest: false,
      isPopular: false,
      isTop: true,
      publishedAt: new Date("2024-01-15T10:00:00Z"),
      createdAt: new Date("2024-01-14T09:00:00Z"),
      updatedAt: new Date("2024-01-16T14:30:00Z"),
    },
    {
      title: "New AI Breakthrough in Natural Language",
      description: "Researchers announce major advances in large language models and real-world applications.",
      content: "Latest developments in AI are transforming how we interact with technology.",
      tags: ["AI", "Technology", "Research"],
      slug: "ai-breakthrough-nlp",
      category: "Sports",
      images: ["/images/news/image-2.png", "/images/news/image-1.png"],
      author: "Jane Smith",
      minutes: 4,
      views: 250,
      status: "published",
      type: "video",
      authorsChoice: true,
      isTrending: true,
      isLatest: true,
      isPopular: false,
      isTop: false,
      publishedAt: new Date("2024-02-20T12:00:00Z"),
      createdAt: new Date("2024-02-19T08:00:00Z"),
      updatedAt: new Date("2024-02-21T11:00:00Z"),
    },
    {
      title: "Climate Summit Reaches Historic Agreement",
      description: "World leaders agree on new emissions targets and green energy investments.",
      content: "The summit concluded with binding commitments from over 150 nations.",
      tags: ["Climate", "Politics", "Environment"],
      slug: "climate-summit-2024",
      category: "Sports",
      images: ["/images/news/image-3.png"],
      author: "Alex Green",
      minutes: 5,
      views: 420,
      status: "published",
      type: "video",
      authorsChoice: false,
      isTrending: true,
      isLatest: false,
      isPopular: true,
      isTop: true,
      publishedAt: new Date("2024-03-05T09:30:00Z"),
      createdAt: new Date("2024-03-04T14:00:00Z"),
      updatedAt: new Date("2024-03-06T16:00:00Z"),
    },
    {
      title: "Mars Rover Discovers Signs of Ancient Water",
      description: "NASA's Perseverance finds compelling evidence of past liquid water on the Red Planet.",
      content: "Scientists are excited about samples that may reveal microbial life traces.",
      tags: ["Space", "NASA", "Mars"],
      slug: "mars-rover-water-discovery",
      category: "Sports",
      images: ["/images/news/image-4.png", "/images/news/image-5.png"],
      author: "Sarah Chen",
      minutes: 6,
      views: 890,
      status: "published",
      type: "video",
      authorsChoice: true,
      isTrending: false,
      isLatest: true,
      isPopular: true,
      isTop: true,
      publishedAt: new Date("2024-03-12T07:00:00Z"),
      createdAt: new Date("2024-03-11T10:00:00Z"),
      updatedAt: new Date("2024-03-13T09:00:00Z"),
    },
    {
      title: "Electric Vehicle Sales Hit Record High",
      description: "Global EV adoption accelerates as prices drop and charging infrastructure expands.",
      content: "Analysts predict EVs will dominate new car sales within the decade.",
      tags: ["EV", "Automotive", "Green"],
      slug: "ev-sales-record-2024",
      category: "Sports",
      images: ["/images/news/image-5.png"],
      author: "Mike Johnson",
      minutes: 4,
      views: 310,
      status: "published",
      type: "video",
      authorsChoice: false,
      isTrending: false,
      isLatest: false,
      isPopular: true,
      isTop: false,
      publishedAt: new Date("2024-04-01T11:00:00Z"),
      createdAt: new Date("2024-03-31T15:00:00Z"),
      updatedAt: new Date("2024-04-02T08:00:00Z"),
    },
    {
      title: "Olympic Games Opening Ceremony Wows Audiences, Spectacular show kicks off the summer games with record viewership. games with record viewership.",
      description: "Olympic Games Opening Ceremony Wows Audiences, Spectacular show kicks off the summer games with record viewership.Olympic Games Opening Ceremony Wows Audiences, Spectacular show kicks off the summer games with record viewership. games with record viewership.",
      content: "Athletes from around the world gathered for the historic opening.",
      tags: ["Olympics", "Sports", "Events"],
      slug: "olympics-opening-2024",
      category: "Sports",
      images: ["/images/news/image-6.png"],
      author: "Emma Wilson",
      minutes: 5,
      views: 1200,
      status: "published",
      type: "video",
      authorsChoice: true,
      isTrending: true,
      isLatest: true,
      isPopular: true,
      isTop: true,
      publishedAt: new Date("2024-07-26T18:00:00Z"),
      createdAt: new Date("2024-07-25T12:00:00Z"),
      updatedAt: new Date("2024-07-27T10:00:00Z"),
    },
    {
      title: "Olympic Games Opening Ceremony Wows Audiences, Spectacular show kicks off the summer games with record viewership. games with record viewership.",
      description: "Olympic Games Opening Ceremony Wows Audiences, Spectacular show kicks off the summer games with record viewership.Olympic Games Opening Ceremony Wows Audiences, Spectacular show kicks off the summer games with record viewership. games with record viewership.",
      content: "Athletes from around the world gathered for the historic opening.",
      tags: ["Olympics", "Sports", "Events"],
      slug: "olympics-opening-2024sd",
      category: "Sports",
      images: ["/images/news/image-6.png"],
      author: "Emma Wilson",
      minutes: 5,
      views: 1200,
      status: "published",
      type: "video",
      authorsChoice: true,
      isTrending: true,
      isLatest: true,
      isPopular: true,
      isTop: true,
      publishedAt: new Date("2024-07-26T18:00:00Z"),
      createdAt: new Date("2024-07-25T12:00:00Z"),
      updatedAt: new Date("2024-07-27T10:00:00Z"),
    },
    {
      title: "Olympic Games Opening Ceremony Wows Audiences, Spectacular show kicks off the summer games with record viewership. games with record viewership.",
      description: "Olympic Games Opening Ceremony Wows Audiences, Spectacular show kicks off the summer games with record viewership.Olympic Games Opening Ceremony Wows Audiences, Spectacular show kicks off the summer games with record viewership. games with record viewership.",
      content: "Athletes from around the world gathered for the historic opening.",
      tags: ["Olympics", "Sports", "Events"],
      slug: "olympics-opening-202d4",
      category: "Sports",
      images: ["/images/news/image-6.png"],
      author: "Emma Wilson",
      minutes: 5,
      views: 1200,
      status: "published",
      type: "video",
      authorsChoice: true,
      isTrending: true,
      isLatest: true,
      isPopular: true,
      isTop: true,
      publishedAt: new Date("2024-07-26T18:00:00Z"),
      createdAt: new Date("2024-07-25T12:00:00Z"),
      updatedAt: new Date("2024-07-27T10:00:00Z"),
    },
    {
      title: "Breakthrough in Quantum Computing Stability",
      description: "Scientists achieve longer coherence times, bringing practical quantum computers closer.",
      content: "The new approach could revolutionize cryptography and drug discovery.",
      tags: ["Quantum", "Computing", "Science"],
      slug: "quantum-computing-stabilityd",
      category: "Business",
      images: ["/images/news/image-7.png", "/images/news/image-8.png"],
      author: "David Park",
      minutes: 6,
      views: 180,
      status: "published",
      type: "image",
      authorsChoice: true,
      isTrending: false,
      isLatest: false,
      isPopular: false,
      isTop: false,
      publishedAt: new Date("2024-05-10T14:00:00Z"),
      createdAt: new Date("2024-05-09T09:00:00Z"),
      updatedAt: new Date("2024-05-11T17:00:00Z"),
    },
    {
      title: "Global Health Organization Reports Progress on Malaria",
      description: "Vaccination campaigns and new treatments show significant reduction in cases.",
      content: "Experts remain cautious but optimistic about eliminating the disease.",
      tags: ["Health", "Malaria", "Vaccine"],
      slug: "malaria-progress-2024",
      category: "Business",
      images: ["/images/news/image-8.png"],
      author: "Lisa Brown",
      minutes: 3,
      views: 95,
      status: "published",
      type: "image",
      authorsChoice: false,
      isTrending: false,
      isLatest: true,
      isPopular: false,
      isTop: false,
      publishedAt: new Date("2024-06-15T08:30:00Z"),
      createdAt: new Date("2024-06-14T11:00:00Z"),
      updatedAt: new Date("2024-06-16T13:00:00Z"),
    },
    {
      title: "Major Film Studio Announces Streaming Strategy Shift, Major Film Studio Announces Streaming Strategy Shift, ",
      description: "Traditional studios pivot to hybrid theatrical and streaming releases.",
      content: "The move reflects changing consumer habits and box office trends.",
      tags: ["Film", "Streaming", "Entertainment"],
      slug: "film-studio-streaming-strategy",
      category: "Business",
      images: ["/images/news/image-9.png"],
      author: "Chris Lee",
      minutes: 5,
      views: 220,
      status: "published",
      type: "image",
      authorsChoice: false,
      isTrending: true,
      isLatest: false,
      isPopular: true,
      isTop: false,
      publishedAt: new Date("2024-08-01T10:00:00Z"),
      createdAt: new Date("2024-07-31T16:00:00Z"),
      updatedAt: new Date("2024-08-02T09:00:00Z"),
    },
    {
      title: "Central Banks Signal Interest Rate Decisions",
      description: "Policy makers weigh inflation data and growth outlook in latest meetings.",
      content: "Markets react to hints of rate cuts in the coming quarters.",
      tags: ["Economy", "Central Bank", "Rates"],
      slug: "central-bank-rates-2025",
      category: "Business",
      images: ["/images/news/image-10.png"],
      author: "Rachel Kim",
      minutes: 7,
      views: 540,
      status: "published",
      type: "image",
      authorsChoice: true,
      isTrending: false,
      isLatest: false,
      isPopular: true,
      isTop: false,
      publishedAt: new Date("2024-09-12T15:00:00Z"),
      createdAt: new Date("2024-09-11T09:00:00Z"),
      updatedAt: new Date("2024-09-13T11:30:00Z"),
    },
    {
      title: "Central Banks Signal Interest Rate Decisions",
      description: "Policy makers weigh inflation data and growth outlook in latest meetings.",
      content: "Markets react to hints of rate cuts in the coming quarters.",
      tags: ["Economy", "Central Bank", "Rates"],
      slug: "central-bank-rates-2024",
      category: "Business",
      images: ["/images/news/image-10.png"],
      author: "Rachel Kim",
      minutes: 7,
      views: 540,
      status: "published",
      type: "image",
      authorsChoice: true,
      isTrending: false,
      isLatest: false,
      isPopular: true,
      isTop: false,
      publishedAt: new Date("2024-09-12T15:00:00Z"),
      createdAt: new Date("2024-09-11T09:00:00Z"),
      updatedAt: new Date("2024-09-13T11:30:00Z"),
    },
    {
      title: "Central Banks Signal Interest Rate Decisions",
      description: "Policy makers weigh inflation data and growth outlook in latest meetings.",
      content: "Markets react to hints of rate cuts in the coming quarters.",
      tags: ["Economy", "Central Bank", "Rates"],
      slug: "central-bank-rates-2023",
      category: "Business",
      images: ["/images/news/image-10.png"],
      author: "Rachel Kim",
      minutes: 7,
      views: 540,
      status: "published",
      type: "image",
      authorsChoice: true,
      isTrending: false,
      isLatest: false,
      isPopular: true,
      isTop: false,
      publishedAt: new Date("2024-09-12T15:00:00Z"),
      createdAt: new Date("2024-09-11T09:00:00Z"),
      updatedAt: new Date("2024-09-13T11:30:00Z"),
    },
    {
      title: "Central Banks Signal Interest Rate Decisions",
      description: "Policy makers weigh inflation data and growth outlook in latest meetings.",
      content: "Markets react to hints of rate cuts in the coming quarters.",
      tags: ["Economy", "Central Bank", "Rates"],
      slug: "central-bank-rates-2024-2",
      category: "Business",
      images: ["/images/news/image-10.png"],
      author: "Rachel Kim",
      minutes: 7,
      views: 540,
      status: "published",
      type: "image",
      authorsChoice: true,
      isTrending: false,
      isLatest: false,
      isPopular: true,
      isTop: false,
      publishedAt: new Date("2024-09-12T15:00:00Z"),
      createdAt: new Date("2024-09-11T09:00:00Z"),
      updatedAt: new Date("2024-09-13T11:30:00Z"),
    },
    {
      title: "How AI Is Changing the Future of Work. A deep dive into the impact of artificial intelligence on jobs and industries.A deep dive into the impact of artificial intelligence on jobs and industries.A deep dive into the impact of artificial intelligence on jobs and industries.A deep dive into the impact of artificial intelligence on jobs and industries.",
      description: "A deep dive into the impact of artificial intelligence on jobs and industries. A deep dive into the impact of artificial intelligence on jobs and industries.A deep dive into the impact of artificial intelligence on jobs and industries.A deep dive into the impact of artificial intelligence on jobs and industries.A deep dive into the impact of artificial intelligence on jobs and industries.A deep dive into the impact of artificial intelligence on jobs and industries.A deep dive into the impact of artificial intelligence on jobs and industries.A deep dive into the impact of artificial intelligence on jobs and industries.A deep dive into the impact of artificial intelligence on jobs and industries.A deep dive into the impact of artificial intelligence on jobs and industries.",
      content: "Experts discuss automation, new roles, and skills needed for the coming decade. Experts discuss automation, new roles, and skills needed for the coming decade.Experts discuss automation, new roles, and skills needed for the coming decade.Experts discuss automation, new roles, and skills needed for the coming decade.Experts discuss automation, new roles, and skills needed for the coming decade.Experts discuss automation, new roles, and skills needed for the coming decade.Experts discuss automation, new roles, and skills needed for the coming decade.Experts discuss automation, new roles, and skills needed for the coming decade.Experts discuss automation, new roles, and skills needed for the coming decade.Experts discuss automation, new roles, and skills needed for the coming decade.",
      tags: ["AI", "Future", "Work"],
      slug: "ai-future-of-work-youtube",
      category: "Business",
      images: ["/images/news/image-2.png", "/images/news/image-3.png", "/images/news/image-4.png", "/images/news/image-5.png"],
      author: "Jane Smith",
      minutes: 8,
      views: 1200,
      status: "published",
      type: "video",
      authorsChoice: true,
      isTrending: true,
      isLatest: true,
      isPopular: true,
      isTop: false,
      publishedAt: new Date("2024-10-01T12:00:00Z"),
      createdAt: new Date("2024-09-30T10:00:00Z"),
      updatedAt: new Date("2024-10-02T09:00:00Z"),
      videoSource: "youtube",
      videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    {
      title: "Local Report: Sports Event Highlights",
      description: "Highlights from the regional sports championship held last week.",
      content: "Full coverage and interviews with athletes and coaches.",
      tags: ["Sports", "Highlights", "Local"],
      slug: "sports-event-highlights-local",
      category: "Sports",
      images: ["/images/news/image-6.png"],
      author: "John Doe",
      minutes: 5,
      views: 450,
      status: "published",
      type: "video",
      authorsChoice: false,
      isTrending: false,
      isLatest: true,
      isPopular: true,
      isTop: false,
      publishedAt: new Date("2024-10-05T14:00:00Z"),
      createdAt: new Date("2024-10-04T11:00:00Z"),
      updatedAt: new Date("2024-10-06T08:00:00Z"),
      videoSource: "local",
      videoUrl: "/videos/news/video-1.mp4",
    },
  ],
};