export const seedNews = {
  news: [
    {
      title: "Nike Air Max 270",
      description: "The Nike Air Max 270 is a modern sneaker that combines comfort and style.",
      content: "The Nike Air Max 270 is a modern sneaker that combines comfort and style.",
      tags: ["Nike", "Air Max", "270"],
      slug: "nike-air-max-270",
      category: "Sports",
      image: "/images/news/image-1.png",
      author: "John Doe",
      views: 100,
      status: "published",
      authorsChoice: true,
      isTrending: false,
      isLatest: false,
      isPopular: false,
      isTop: true,
      publishedAt: new Date("2024-01-15T10:00:00Z"),
      createdAt: new Date("2024-01-14T09:00:00Z"),
      updatedAt: new Date("2024-01-16T14:30:00Z"),
    },
    {
      title: "New AI Breakthrough in Natural Language",
      description: "Researchers announce major advances in large language models and real-world applications.",
      content: "Latest developments in AI are transforming how we interact with technology.",
      tags: ["AI", "Technology", "Research"],
      slug: "ai-breakthrough-nlp",
      category: "Technology",
      image: "/images/news/image-2.png",
      author: "Jane Smith",
      views: 250,
      status: "published",
      authorsChoice: true,
      isTrending: true,
      isLatest: true,
      isPopular: false,
      isTop: false,
      publishedAt: new Date("2024-02-20T12:00:00Z"),
      createdAt: new Date("2024-02-19T08:00:00Z"),
      updatedAt: new Date("2024-02-21T11:00:00Z"),
    },
    {
      title: "Climate Summit Reaches Historic Agreement",
      description: "World leaders agree on new emissions targets and green energy investments.",
      content: "The summit concluded with binding commitments from over 150 nations.",
      tags: ["Climate", "Politics", "Environment"],
      slug: "climate-summit-2024",
      category: "Politics",
      image: "/images/news/image-3.png",
      author: "Alex Green",
      views: 420,
      status: "published",
      authorsChoice: false,
      isTrending: true,
      isLatest: false,
      isPopular: true,
      isTop: true,
      publishedAt: new Date("2024-03-05T09:30:00Z"),
      createdAt: new Date("2024-03-04T14:00:00Z"),
      updatedAt: new Date("2024-03-06T16:00:00Z"),
    },
    {
      title: "Mars Rover Discovers Signs of Ancient Water",
      description: "NASA's Perseverance finds compelling evidence of past liquid water on the Red Planet.",
      content: "Scientists are excited about samples that may reveal microbial life traces.",
      tags: ["Space", "NASA", "Mars"],
      slug: "mars-rover-water-discovery",
      category: "Science",
      image: "/images/news/image-4.png",
      author: "Sarah Chen",
      views: 890,
      status: "published",
      authorsChoice: true,
      isTrending: false,
      isLatest: true,
      isPopular: true,
      isTop: true,
      publishedAt: new Date("2024-03-12T07:00:00Z"),
      createdAt: new Date("2024-03-11T10:00:00Z"),
      updatedAt: new Date("2024-03-13T09:00:00Z"),
    },
    {
      title: "Electric Vehicle Sales Hit Record High",
      description: "Global EV adoption accelerates as prices drop and charging infrastructure expands.",
      content: "Analysts predict EVs will dominate new car sales within the decade.",
      tags: ["EV", "Automotive", "Green"],
      slug: "ev-sales-record-2024",
      category: "Business",
      image: "/images/news/image-5.png",
      author: "Mike Johnson",
      views: 310,
      status: "published",
      authorsChoice: false,
      isTrending: false,
      isLatest: false,
      isPopular: true,
      isTop: false,
      publishedAt: new Date("2024-04-01T11:00:00Z"),
      createdAt: new Date("2024-03-31T15:00:00Z"),
      updatedAt: new Date("2024-04-02T08:00:00Z"),
    },
    {
      title: "Olympic Games Opening Ceremony Wows Audiences, Spectacular show kicks off the summer games with record viewership.",
      description: "Olympic Games Opening Ceremony Wows Audiences, Spectacular show kicks off the summer games with record viewership.Olympic Games Opening Ceremony Wows Audiences, Spectacular show kicks off the summer games with record viewership.",
      content: "Athletes from around the world gathered for the historic opening.",
      tags: ["Olympics", "Sports", "Events"],
      slug: "olympics-opening-2024",
      category: "Sports",
      image: "/images/news/image-6.png",
      author: "Emma Wilson",
      views: 1200,
      status: "published",
      authorsChoice: true,
      isTrending: true,
      isLatest: true,
      isPopular: true,
      isTop: true,
      publishedAt: new Date("2024-07-26T18:00:00Z"),
      createdAt: new Date("2024-07-25T12:00:00Z"),
      updatedAt: new Date("2024-07-27T10:00:00Z"),
    },
    {
      title: "Breakthrough in Quantum Computing Stability",
      description: "Scientists achieve longer coherence times, bringing practical quantum computers closer.",
      content: "The new approach could revolutionize cryptography and drug discovery.",
      tags: ["Quantum", "Computing", "Science"],
      slug: "quantum-computing-stability",
      category: "Technology",
      image: "/images/news/image-7.png",
      author: "David Park",
      views: 180,
      status: "published",
      authorsChoice: true,
      isTrending: false,
      isLatest: false,
      isPopular: false,
      isTop: false,
      publishedAt: new Date("2024-05-10T14:00:00Z"),
      createdAt: new Date("2024-05-09T09:00:00Z"),
      updatedAt: new Date("2024-05-11T17:00:00Z"),
    },
    {
      title: "Global Health Organization Reports Progress on Malaria",
      description: "Vaccination campaigns and new treatments show significant reduction in cases.",
      content: "Experts remain cautious but optimistic about eliminating the disease.",
      tags: ["Health", "Malaria", "Vaccine"],
      slug: "malaria-progress-2024",
      category: "Health",
      image: "/images/news/image-8.png",
      author: "Lisa Brown",
      views: 95,
      status: "published",
      authorsChoice: false,
      isTrending: false,
      isLatest: true,
      isPopular: false,
      isTop: false,
      publishedAt: new Date("2024-06-15T08:30:00Z"),
      createdAt: new Date("2024-06-14T11:00:00Z"),
      updatedAt: new Date("2024-06-16T13:00:00Z"),
    },
    {
      title: "Major Film Studio Announces Streaming Strategy Shift, Major Film Studio Announces Streaming Strategy Shift, ",
      description: "Traditional studios pivot to hybrid theatrical and streaming releases.",
      content: "The move reflects changing consumer habits and box office trends.",
      tags: ["Film", "Streaming", "Entertainment"],
      slug: "film-studio-streaming-strategy",
      category: "Entertainment",
      image: "/images/news/image-9.png",
      author: "Chris Lee",
      views: 220,
      status: "published",
      authorsChoice: false,
      isTrending: true,
      isLatest: false,
      isPopular: true,
      isTop: false,
      publishedAt: new Date("2024-08-01T10:00:00Z"),
      createdAt: new Date("2024-07-31T16:00:00Z"),
      updatedAt: new Date("2024-08-02T09:00:00Z"),
    },
    {
      title: "Central Banks Signal Interest Rate Decisions",
      description: "Policy makers weigh inflation data and growth outlook in latest meetings.",
      content: "Markets react to hints of rate cuts in the coming quarters.",
      tags: ["Economy", "Central Bank", "Rates"],
      slug: "central-bank-rates-2024",
      category: "Business",
      image: "/images/news/image-10.png",
      author: "Rachel Kim",
      views: 540,
      status: "published",
      authorsChoice: true,
      isTrending: false,
      isLatest: false,
      isPopular: true,
      isTop: false,
      publishedAt: new Date("2024-09-12T15:00:00Z"),
      createdAt: new Date("2024-09-11T09:00:00Z"),
      updatedAt: new Date("2024-09-13T11:30:00Z"),
    },
  ],
};