import type { RawNewsItem, NewsStatus } from "@/features/news/model"
import type { NewsContent } from "@/features/news/model"

function t(uz: string, uzb?: string, ru?: string, en?: string) {
  return { uz, uzb, ru, en }
}

function d(uz?: string, uzb?: string, ru?: string, en?: string) {
  return { uz, uzb, ru, en }
}

const contentNikeRich: NewsContent = [
  { type: "paragraph", text: "The Nike Air Max 270 is a modern sneaker that combines comfort and style. It features a large Air unit for all-day cushioning." },
  { type: "image", src: "/images/news/image-1.png", alt: "Nike Air Max 270 side view" },
  { type: "quote", text: "The most comfortable Air Max we've ever made.", author: "Nike Design Team" },
  { type: "paragraph", text: "Available in multiple colorways. Learn more at the official store." },
  { type: "video", source: "youtube", url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ" },
  { type: "video", source: "local", url: "/videos/news/video-1.mp4" },
  { type: "link", href: "https://www.nike.com", text: "Nike Official Store" },
]

export const seedNews: { news: RawNewsItem[] } = {
  news: [
    {
      slug: "nike-air-max-270",
      title: t("Nike Air Max 270", "Nike Air Max 270", "Nike Air Max 270", "Nike Air Max 270"),
      description: d(
        "The Nike Air Max 270 is a modern sneaker that combines comfort and style.",
        undefined,
        "Nike Air Max 270 — zamonaviy krossovki, qulaylik va uslubni birlashtiradi.",
        "The Nike Air Max 270 is a modern sneaker that combines comfort and style."
      ),
      content: { uz: contentNikeRich, uzb: contentNikeRich, ru: contentNikeRich, en: contentNikeRich },
      categorySlug: "sports",
      tagSlugs: ["nike", "air-max", "270"],
      images: ["/images/news/image-1.png", "/images/news/image-2.png", "/images/news/image-3.png"],
      author: "John Doe",
      minutes: 3,
      views: 100,
      status: "published" as NewsStatus,
      pushedToTelegram: false,
      type: "video",
      authorsChoice: true,
      isTrending: false,
      isLatest: false,
      isPopular: false,
      isTop: true,
      videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      publishedAt: new Date("2024-01-15T10:00:00Z"),
      createdAt: new Date("2024-01-14T09:00:00Z"),
      updatedAt: new Date("2024-01-16T14:30:00Z"),
    },
    {
      slug: "ai-breakthrough-nlp",
      title: t("Sun'iy intellektda tabiiy til bo'yicha yutuq", "Сунъий интеллектда табиий тил бўйича ютуқ", "Прорыв в области ИИ и естественного языка", "New AI Breakthrough in Natural Language"),
      description: d(
        "Tadqiqotchilar katta til modellari va amaliy qo'llanmalar bo'yicha muhim yutuqlar e'lon qildi.",
        "Тадқиқотчилар катта тил модели ва амалий қўllanмалар бўйича муҳим ютуқлар элон қилди.",
        "Исследователи объявили о крупных достижениях в больших языковых моделях.",
        "Researchers announce major advances in large language models and real-world applications."
      ),
      content: d(
        "Sun'iy intellekt so'nggi yutuqlari texnologiya bilan muloqotimizni o'zgartirmoqda.",
        undefined,
        "Последние разработки в области ИИ меняют то, как мы взаимодействуем с технологиями.",
        "Latest developments in AI are transforming how we interact with technology."
      ),
      categorySlug: "sports",
      tagSlugs: ["ai", "technology", "research"],
      images: ["/images/news/image-2.png", "/images/news/image-1.png"],
      author: "Jane Smith",
      minutes: 4,
      views: 250,
      status: "pending" as NewsStatus,
      pushedToTelegram: false,
      type: "video",
      authorsChoice: true,
      isTrending: true,
      isLatest: true,
      isPopular: false,
      isTop: false,
      publishedAt: new Date("2024-02-20T12:00:00Z"),
      createdAt: new Date("2024-02-19T08:00:00Z"),
      updatedAt: new Date("2024-02-21T11:00:00Z"),
    },
    {
      slug: "climate-summit-2024",
      title: t("Iqlim sammiti tarixiy kelishuvga erishdi", "Иқлим саммити тарихий келишувга эришди", "Климатический саммит достиг исторического соглашения", "Climate Summit Reaches Historic Agreement"),
      description: d(
        "Dunyo yetakchilari yangi emissiya maqsadlari va yashil energiya sarmoyalari bo'yicha kelishdi.",
        undefined,
        "Мировые лидеры договорились о новых целях по выбросам и «зелёных» инвестициях.",
        "World leaders agree on new emissions targets and green energy investments."
      ),
      content: d(
        "Sammit 150 dan ortiq mamlakatlarning majburiy majburiyatlari bilan yakunlandi.",
        undefined,
        "Саммит завершился обязательными обязательствами более 150 стран.",
        "The summit concluded with binding commitments from over 150 nations."
      ),
      categorySlug: "sports",
      tagSlugs: ["climate", "politics", "environment"],
      images: ["/images/news/image-3.png"],
      author: "Alex Green",
      minutes: 5,
      views: 420,
      status: "published" as NewsStatus,
      pushedToTelegram: false,
      type: "video",
      authorsChoice: false,
      isTrending: true,
      isLatest: false,
      isPopular: true,
      isTop: true,
      publishedAt: new Date("2024-03-05T09:30:00Z"),
      createdAt: new Date("2024-03-04T14:00:00Z"),
      updatedAt: new Date("2024-03-06T16:00:00Z"),
    },
    {
      slug: "mars-rover-water-discovery",
      title: t("Mars roveri qadimiy suv izlarini topdi", "Марс ровери қадимiy сув изларини топди", "Марсоход NASA нашёл следы древней воды", "Mars Rover Discovers Signs of Ancient Water"),
      description: d(
        "NASA Perseverance Qizil sayyorada suyuq suv borligining ishonchli dalillarini topdi.",
        undefined,
        "Perseverance нашёл убедительные доказательства прошлой жидкой воды на Марсе.",
        "NASA's Perseverance finds compelling evidence of past liquid water on the Red Planet."
      ),
      content: d(
        "Olimlar namunalar mikrobial hayot izlarini ochishi mumkinligi haqida hayajondalar.",
        undefined,
        "Учёные взволнованы образцами, которые могут выявить следы микробной жизни.",
        "Scientists are excited about samples that may reveal microbial life traces."
      ),
      categorySlug: "sports",
      tagSlugs: ["space", "nasa", "mars"],
      images: ["/images/news/image-4.png", "/images/news/image-5.png"],
      author: "Sarah Chen",
      minutes: 6,
      views: 890,
      status: "published" as NewsStatus,
      pushedToTelegram: false,
      type: "video",
      authorsChoice: true,
      isTrending: false,
      isLatest: true,
      isPopular: true,
      isTop: true,
      publishedAt: new Date("2024-03-12T07:00:00Z"),
      createdAt: new Date("2024-03-11T10:00:00Z"),
      updatedAt: new Date("2024-03-13T09:00:00Z"),
    },
    {
      slug: "ev-sales-record-2024",
      title: t("Elektromobillar savdosi rekord darajaga yetdi", "Электромобиллар савдоси рекорд даражага етди", "Продажи электромобилей достигли рекорда", "Electric Vehicle Sales Hit Record High"),
      description: d(
        "Narxlar tushishi va zaryadlash infratuzilmasi kengayishi bilan EV ulushi oshmoqda.",
        undefined,
        "Глобальная доля электромобилей растёт по мере снижения цен и расширения зарядной сети.",
        "Global EV adoption accelerates as prices drop and charging infrastructure expands."
      ),
      content: d(
        "Tahlilchilar o'n yil ichida yangi avtomobillar savdosida EV ustun bo'lishini bashorat qilmoqda.",
        undefined,
        "Аналитики предсказывают доминирование электромобилей в продажах в течение десятилетия.",
        "Analysts predict EVs will dominate new car sales within the decade."
      ),
      categorySlug: "sports",
      tagSlugs: ["ev", "automotive", "green"],
      images: ["/images/news/image-5.png"],
      author: "Mike Johnson",
      minutes: 4,
      views: 310,
      status: "published" as NewsStatus,
      pushedToTelegram: false,
      type: "video",
      authorsChoice: false,
      isTrending: false,
      isLatest: false,
      isPopular: true,
      isTop: false,
      publishedAt: new Date("2024-04-01T11:00:00Z"),
      createdAt: new Date("2024-03-31T15:00:00Z"),
      updatedAt: new Date("2024-04-02T08:00:00Z"),
    },
    {
      slug: "olympics-opening-2024",
      title: t("Olimpiada ochilish marosimi tomoshabinlarni hayratga soldi", "Олимпиада очилиш маросими томошабинларни ҳайратга солди", "Церемония открытия Олимпиады восхитила зрителей", "Olympic Games Opening Ceremony Wows Audiences"),
      description: d(
        "Yozgi o'yinlarning daho ochilish marosimi rekord tomoshabinlar soni bilan boshlandi.",
        undefined,
        "Эффектная церемония открытия летних игр собрала рекордную телеаудиторию.",
        "Spectacular show kicks off the summer games with record viewership."
      ),
      content: d(
        "Dunyo atletlari tarixiy ochilish uchun yig'ilishdi.",
        undefined,
        "Спортсмены со всего мира собрались на историческое открытие.",
        "Athletes from around the world gathered for the historic opening."
      ),
      categorySlug: "sports",
      tagSlugs: ["olympics", "sport", "events"],
      images: ["/images/news/image-6.png"],
      author: "Emma Wilson",
      minutes: 5,
      views: 1200,
      status: "published" as NewsStatus,
      pushedToTelegram: false,
      type: "video",
      authorsChoice: true,
      isTrending: true,
      isLatest: true,
      isPopular: true,
      isTop: true,
      publishedAt: new Date("2024-07-26T18:00:00Z"),
      createdAt: new Date("2024-07-25T12:00:00Z"),
      updatedAt: new Date("2024-07-27T10:00:00Z"),
    },
    {
      slug: "olympics-opening-2024sd",
      title: t("Olimpiada ochilish marosimi tomoshabinlarni hayratga soldi"),
      description: d("Yozgi o'yinlarning daho ochilish marosimi rekord tomoshabinlar soni bilan boshlandi."),
      content: d("Dunyo atletlari tarixiy ochilish uchun yig'ilishdi."),
      categorySlug: "sports",
      tagSlugs: ["olympics", "sport", "events"],
      images: ["/images/news/image-6.png"],
      author: "Emma Wilson",
      minutes: 5,
      views: 1200,
      status: "published" as NewsStatus,
      pushedToTelegram: false,
      type: "video",
      authorsChoice: true,
      isTrending: true,
      isLatest: true,
      isPopular: true,
      isTop: true,
      publishedAt: new Date("2024-07-26T18:00:00Z"),
      createdAt: new Date("2024-07-25T12:00:00Z"),
      updatedAt: new Date("2024-07-27T10:00:00Z"),
    },
    {
      slug: "olympics-opening-202d4",
      title: t("Olimpiada ochilish marosimi"),
      categorySlug: "sports",
      tagSlugs: ["olympics", "sport", "events"],
      images: ["/images/news/image-6.png"],
      author: "Emma Wilson",
      minutes: 5,
      views: 1200,
      status: "published" as NewsStatus,
      pushedToTelegram: false,
      type: "video",
      authorsChoice: true,
      isTrending: true,
      isLatest: true,
      isPopular: true,
      isTop: true,
      publishedAt: new Date("2024-07-26T18:00:00Z"),
      createdAt: new Date("2024-07-25T12:00:00Z"),
      updatedAt: new Date("2024-07-27T10:00:00Z"),
    },
    {
      slug: "quantum-computing-stabilityd",
      title: t("Kvant hisoblashda barqarorlik bo'yicha yutuq", "Квант хисоблашда барқарорлик бўйича ютуқ", "Прорыв в стабильности квантовых вычислений", "Breakthrough in Quantum Computing Stability"),
      description: d(
        "Olimlar uzoqroq uyg'unlik vaqtiga erishib, amaliy kvant kompyuterlarni yaqinlashtirmoqda.",
        undefined,
        "Учёные достигли большей когерентности, приблизив практические квантовые компьютеры.",
        "Scientists achieve longer coherence times, bringing practical quantum computers closer."
      ),
      content: d(
        "Yondashuv kriptografiya va dori topishda inqilob qilishi mumkin.",
        undefined,
        "Новый подход может революционизировать криптографию и поиск лекарств.",
        "The new approach could revolutionize cryptography and drug discovery."
      ),
      categorySlug: "business",
      tagSlugs: ["quantum", "computing", "science"],
      images: ["/images/news/image-7.png", "/images/news/image-8.png"],
      author: "David Park",
      minutes: 6,
      views: 180,
      status: "archived" as NewsStatus,
      pushedToTelegram: false,
      type: "image",
      authorsChoice: true,
      isTrending: false,
      isLatest: false,
      isPopular: false,
      isTop: false,
      publishedAt: new Date("2024-05-10T14:00:00Z"),
      createdAt: new Date("2024-05-09T09:00:00Z"),
      updatedAt: new Date("2024-05-11T17:00:00Z"),
    },
    {
      slug: "malaria-progress-2024",
      title: t("Jahon sog'liqni saqlash tashkiloti malariya bo'yicha yutuq xabar qildi", "Жаҳон согликни сақлаш ташкилоти малярия бўйича ютуқ хабар қилди", "ВОЗ сообщила о прогрессе в борьбе с малярией", "Global Health Organization Reports Progress on Malaria"),
      description: d(
        "Emlash va yangi davolash usullari bemorlar sonini sezilarli kamaytirdi.",
        undefined,
        "Кампании вакцинации и новые методы лечения значительно снизили заболеваемость.",
        "Vaccination campaigns and new treatments show significant reduction in cases."
      ),
      content: d(
        "Ekspertlar ehtiyotkor, lekin kasallikni yo'q qilish borasida ishonchli.",
        undefined,
        "Эксперты осторожны, но настроены оптимистично в отношении ликвидации болезни.",
        "Experts remain cautious but optimistic about eliminating the disease."
      ),
      categorySlug: "business",
      tagSlugs: ["health", "malaria", "vaccine"],
      images: ["/images/news/image-8.png"],
      author: "Lisa Brown",
      minutes: 3,
      views: 95,
      status: "cancelled" as NewsStatus,
      pushedToTelegram: false,
      type: "image",
      authorsChoice: false,
      isTrending: false,
      isLatest: true,
      isPopular: false,
      isTop: false,
      publishedAt: new Date("2024-06-15T08:30:00Z"),
      createdAt: new Date("2024-06-14T11:00:00Z"),
      updatedAt: new Date("2024-06-16T13:00:00Z"),
    },
    {
      slug: "film-studio-streaming-strategy",
      title: t("Yirik kino studiyasi striming strategiyasini o'zgartirdi", "Йирик кино студияси стриминг стратегиясини ўзгартирди", "Крупная киностудия объявила смену стратегии стриминга", "Major Film Studio Announces Streaming Strategy Shift"),
      description: d(
        "An'anaviy studiyalar kinoteatr va strimingni birlashtirgan relizlarga o'tmoqda.",
        undefined,
        "Традиционные студии переходят на гибридный кинопрокат и стриминг.",
        "Traditional studios pivot to hybrid theatrical and streaming releases."
      ),
      content: d(
        "Qaror iste'molchilar odatlari va kassa tendensiyalarini aks ettiradi.",
        undefined,
        "Решение отражает изменение потребительских привычек и кассовых трендов.",
        "The move reflects changing consumer habits and box office trends."
      ),
      categorySlug: "business",
      tagSlugs: ["film", "streaming", "entertainment"],
      images: ["/images/news/image-9.png"],
      author: "Chris Lee",
      minutes: 5,
      views: 220,
      status: "published" as NewsStatus,
      pushedToTelegram: false,
      type: "image",
      authorsChoice: false,
      isTrending: true,
      isLatest: false,
      isPopular: true,
      isTop: false,
      publishedAt: new Date("2024-08-01T10:00:00Z"),
      createdAt: new Date("2024-07-31T16:00:00Z"),
      updatedAt: new Date("2024-08-02T09:00:00Z"),
    },
    {
      slug: "central-bank-rates-2025",
      title: t("Markaziy banklar foiz stavkalari qarorini bildirdi", "Марказий банклар фоиз ставкалари қарорини билдирди", "Центробанки обозначили решение по ставкам", "Central Banks Signal Interest Rate Decisions"),
      description: d(
        "Politika qiluvchilar inflyatsiya va o'sish ma'lumotlarini ko'rib chiqmoqda.",
        undefined,
        "Политики взвешивают данные по инфляции и перспективам роста.",
        "Policy makers weigh inflation data and growth outlook in latest meetings."
      ),
      content: d(
        "Bozorlar kelgusi choraklarda stavka pasayishi haqidagi taxminlarga javob bermoqda.",
        undefined,
        "Рынки реагируют на намёки снижения ставок в ближайших кварталах.",
        "Markets react to hints of rate cuts in the coming quarters."
      ),
      categorySlug: "business",
      tagSlugs: ["economy", "central-bank", "rates"],
      images: ["/images/news/image-10.png"],
      author: "Rachel Kim",
      minutes: 7,
      views: 540,
      status: "published" as NewsStatus,
      pushedToTelegram: false,
      type: "image",
      authorsChoice: true,
      isTrending: false,
      isLatest: false,
      isPopular: true,
      isTop: false,
      publishedAt: new Date("2024-09-12T15:00:00Z"),
      createdAt: new Date("2024-09-11T09:00:00Z"),
      updatedAt: new Date("2024-09-13T11:30:00Z"),
    },
    {
      slug: "central-bank-rates-2024",
      title: t("Markaziy banklar foiz stavkalari qarorini bildirdi"),
      description: d("Politika qiluvchilar inflyatsiya va o'sish ma'lumotlarini ko'rib chiqmoqda."),
      content: d("Bozorlar kelgusi choraklarda stavka pasayishi haqidagi taxminlarga javob bermoqda."),
      categorySlug: "business",
      tagSlugs: ["economy", "central-bank", "rates"],
      images: ["/images/news/image-10.png"],
      author: "Rachel Kim",
      minutes: 7,
      views: 540,
      status: "published" as NewsStatus,
      pushedToTelegram: false,
      type: "image",
      authorsChoice: true,
      isTrending: false,
      isLatest: false,
      isPopular: true,
      isTop: false,
      publishedAt: new Date("2024-09-12T15:00:00Z"),
      createdAt: new Date("2024-09-11T09:00:00Z"),
      updatedAt: new Date("2024-09-13T11:30:00Z"),
    },
    {
      slug: "central-bank-rates-2023",
      title: t("Markaziy banklar foiz stavkalari"),
      categorySlug: "business",
      tagSlugs: ["economy", "central-bank", "rates"],
      images: ["/images/news/image-10.png"],
      author: "Rachel Kim",
      minutes: 7,
      views: 540,
      status: "published" as NewsStatus,
      pushedToTelegram: false,
      type: "image",
      authorsChoice: true,
      isTrending: false,
      isLatest: false,
      isPopular: true,
      isTop: false,
      publishedAt: new Date("2024-09-12T15:00:00Z"),
      createdAt: new Date("2024-09-11T09:00:00Z"),
      updatedAt: new Date("2024-09-13T11:30:00Z"),
    },
    {
      slug: "central-bank-rates-2024-2",
      title: t("Markaziy banklar stavkalari 2024"),
      categorySlug: "business",
      tagSlugs: ["economy", "central-bank", "rates"],
      images: ["/images/news/image-10.png"],
      author: "Rachel Kim",
      minutes: 7,
      views: 540,
      status: "published" as NewsStatus,
      pushedToTelegram: false,
      type: "image",
      authorsChoice: true,
      isTrending: false,
      isLatest: false,
      isPopular: true,
      isTop: false,
      publishedAt: new Date("2024-09-12T15:00:00Z"),
      createdAt: new Date("2024-09-11T09:00:00Z"),
      updatedAt: new Date("2024-09-13T11:30:00Z"),
    },
    {
      slug: "ai-future-of-work-youtube",
      title: t("Sun'iy intellekt ishning kelajagini qanday o'zgartirmoqda", "Сунъий интеллект ишнинг келажагини қандай ўзгартирмоқда", "Как ИИ меняет будущее труда", "How AI Is Changing the Future of Work"),
      description: d(
        "Sun'iy intellektning ish o'rinlari va sanoatga ta'siri haqida chuqur ma'lumot.",
        undefined,
        "Глубокий обзор влияния ИИ на рабочие места и отрасли.",
        "A deep dive into the impact of artificial intelligence on jobs and industries."
      ),
      content: d(
        "Ekspertlar avtomatlashtirish, yangi rollar va kelgusi o'n yil uchun kerakli ko'nikmalar haqida muhokama qilmoqda.",
        undefined,
        "Эксперты обсуждают автоматизацию, новые роли и навыки на следующее десятилетие.",
        "Experts discuss automation, new roles, and skills needed for the coming decade."
      ),
      categorySlug: "business",
      tagSlugs: ["ai", "future", "work"],
      images: ["/images/news/image-2.png", "/images/news/image-3.png", "/images/news/image-4.png", "/images/news/image-5.png"],
      author: "Jane Smith",
      minutes: 8,
      views: 1200,
      status: "published" as NewsStatus,
      pushedToTelegram: false,
      type: "video",
      authorsChoice: true,
      isTrending: true,
      isLatest: true,
      isPopular: true,
      isTop: false,
      publishedAt: new Date("2024-10-01T12:00:00Z"),
      createdAt: new Date("2024-09-30T10:00:00Z"),
      updatedAt: new Date("2024-10-02T09:00:00Z"),
      videoSource: "youtube",
      videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    {
      slug: "sports-event-highlights-local",
      title: t("Mahalliy hisobot: sport tadbirining asosiy voqeaları", "Маҳаллий хисобот: спорт тадбирининг асосий воқеалари", "Местный отчёт: главные моменты спортивного события", "Local Report: Sports Event Highlights"),
      description: d(
        "O'tgan hafta bo'lib o'tgan mintaqaviy sport chempionatining asosiy voqeaları.",
        undefined,
        "Главные моменты регионального спортивного чемпионата на прошлой неделе.",
        "Highlights from the regional sports championship held last week."
      ),
      content: d(
        "Atletlar va murabbiylar bilan to'liq reportaj va intervyular.",
        undefined,
        "Полный репортаж и интервью с атлетами и тренерами.",
        "Full coverage and interviews with athletes and coaches."
      ),
      categorySlug: "sports",
      tagSlugs: ["sport", "highlights", "local"],
      images: ["/images/news/image-6.png"],
      author: "John Doe",
      minutes: 5,
      views: 450,
      status: "published" as NewsStatus,
      pushedToTelegram: false,
      type: "video",
      authorsChoice: false,
      isTrending: false,
      isLatest: true,
      isPopular: true,
      isTop: false,
      publishedAt: new Date("2024-10-05T14:00:00Z"),
      createdAt: new Date("2024-10-04T11:00:00Z"),
      updatedAt: new Date("2024-10-06T08:00:00Z"),
      videoSource: "local",
      videoUrl: "/videos/news/video-1.mp4",
    },
  ],
}
